// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using faturamento_api.Data;

#nullable disable

namespace faturamento_api.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    [Migration("20251110011756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("nota_numeracao_sequence");

            modelBuilder.Entity("faturamento_api.Entities.IdempotencyKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("RespostaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusHttp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Chave", "Rota")
                        .IsUnique();

                    b.ToTable("ChaveIdempotencia");
                });

            modelBuilder.Entity("faturamento_api.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('nota_numeracao_sequence')");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Nota", t =>
                        {
                            t.HasCheckConstraint("CK_Nota_Status", "\"Status\" IN ('Aberta','Fechada')");
                        });
                });

            modelBuilder.Entity("faturamento_api.Entities.NotaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotaId", "ProdutoId");

                    b.ToTable("NotaItem", t =>
                        {
                            t.HasCheckConstraint("CK_NotaItem_Quantidade_Pos", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("faturamento_api.Entities.NotaItem", b =>
                {
                    b.HasOne("faturamento_api.Entities.Nota", null)
                        .WithMany("Itens")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("faturamento_api.Entities.Nota", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
